image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main  # ветка git

build: off
install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew

  build_script:
    - ./gradlew test --info -Dselenide.headless=true